### PR TITLE
Add docs for iam_group and correct typo in iam-access-key sidebar.

### PR DESCRIPTION
**Pull request by ctiwald**
Adding some sidebar logic left out of my original patch, the iam_group docs, and correcting a minor type in the iam-access-key sidebar.

### CODE REVIEW

**Comment by ctiwald** [comment]
Newest rebase corrects some dumb typos I made in `aws.erb` and adds new docs. I'm going to keep appending commits to this until I can no longer work on it or it's done. In either case, I'll post here, @bitglue.

**Comment by ctiwald** [comment]
Got about half of these ready to go. Aiming to finish the rest this afternoon.

**Comment by ctiwald** [comment]
Alright. Right now this should be everything but iam-role. @bitglue if you want to merge and just crank that out, that's fine. Otherwise I'll try to find 10 minutes tomorrow to knock it out.

**Comment by bitglue** [comment]
Merged these changes with some rebasing: they are now included in https://github.com/hashicorp/terraform/pull/939. Thanks for the help!

**Comment by bitglue** [comment]
@ctiwald oh also if you do iam-role tomorrow just open another PR. I doubt I'll get to it by then. Also if you base your branch off my iam branch that will make the merging a little easier since I won't have to rebase, which confuses poor github. I maintain the master branch with the IAM changes, and all my other open PRs.

**Pull request closed without merging**
